// lib/db/types.ts — shared types for the database abstraction layer

export interface User {
  id: string;
  username: string;
  createdAt: number;
}

export interface Passkey {
  id: string;
  userId: string;
  credentialId: string;
  publicKey: Uint8Array;
  counter: number;
  deviceType: string;
  backedUp: boolean;
  transports: string | null; // comma-separated list e.g. "internal,hybrid"
  createdAt: number;
}

export interface Challenge {
  id: string;
  challenge: string;
  userId: string | null;
  username: string | null;
  expiresAt: number;
}

export interface Session {
  id: string;
  userId: string;
  expiresAt: number;
}

/**
 * A short-lived token that coordinates cross-device authentication.
 * The "requester" device (e.g. laptop) creates one and shows a QR code.
 * The "approver" device (e.g. phone, already signed in) scans the QR and
 * approves it; the requester then polls until approved and gets a session.
 *
 * API-key encryption key transfer (ECDH):
 *   - The requester generates an ephemeral ECDH key pair and stores the public
 *     key here so the approver can use it.
 *   - The approver generates its own ephemeral ECDH key pair, derives the ECDH
 *     shared secret, wraps its AES storage key, and stores the wrapped bundle
 *     plus its public key here.
 *   - The requester retrieves both via the poll response and unwraps the AES key.
 */
export interface CrossDeviceToken {
  id: string;
  /** "pending" → created, waiting for approval; "approved" → approver clicked approve */
  status: "pending" | "approved";
  /** Set when the approver approves — the userId of the approving user. */
  userId: string | null;
  expiresAt: number;
  /** Requester's ephemeral ECDH P-256 public key as a JWK JSON string (set at token creation). */
  requesterEcdhPublicKey: string | null;
  /** Approver's ephemeral ECDH P-256 public key as a JWK JSON string (set on approval). */
  approverEcdhPublicKey: string | null;
  /** AES storage key wrapped by the ECDH-derived key, as JSON `{ iv, ciphertext }` (set on approval). */
  wrappedAesKey: string | null;
}

/**
 * A persisted record of one local evolve session.
 * In-memory sessions also carry a ChildProcess reference (not stored here).
 */
export interface EvolveSession {
  id: string;
  branch: string;
  worktreePath: string;
  /** One of the LocalSessionStatus values serialised as a string. */
  status: string;
  port: number | null;
  previewUrl: string | null;
  /** The original change request submitted by the user. */
  request: string;
  createdAt: number;
  /** Wall-clock duration of the Claude run in milliseconds (null until complete). */
  durationMs: number | null;
  /** Number of input tokens consumed by the Claude run (null until complete). */
  inputTokens: number | null;
  /** Number of output tokens generated by the Claude run (null until complete). */
  outputTokens: number | null;
  /** Total API cost in USD for the Claude run (null until complete). */
  costUsd: number | null;
}

export interface Role {
  id: string;
  name: string;
  displayName: string;
  description: string;
  createdAt: number;
}

/** This instance's identity and settings. */
export interface InstanceConfig {
  uuid7: string;
  name: string;
  description: string;
  /** The public-facing URL of this instance (e.g. https://primordia.example.com). */
  canonicalUrl: string;
  /** URL of the parent instance to register with (empty string = no parent). */
  parentUrl: string;
}

/** A known peer Primordia instance in the social graph. */
export interface GraphNode {
  uuid7: string;
  /** Current canonical URL, or empty string if unknown. */
  url: string;
  name: string;
  description: string | null;
  registeredAt: number;
}

/** A directed relationship between two instances. */
export interface GraphEdge {
  id: string;
  from: string; // uuid7
  to: string;   // uuid7
  type: string; // e.g. "fork"
  date: string; // ISO date string YYYY-MM-DD
  createdAt: number;
}

export interface UserPreferences {
  userId: string;
  key: string;
  value: string;
  updatedAt: number;
}

export interface DbAdapter {
  // Users
  createUser(user: User): Promise<void>;
  getUserByUsername(username: string): Promise<User | null>;
  getUserById(id: string): Promise<User | null>;
  getAllUsers(): Promise<User[]>;
  getFirstUser(): Promise<User | null>;

  // Passkeys
  savePasskey(passkey: Passkey): Promise<void>;
  getPasskeysByUserId(userId: string): Promise<Passkey[]>;
  getPasskeyByCredentialId(credentialId: string): Promise<Passkey | null>;
  updatePasskeyCounter(credentialId: string, counter: number): Promise<void>;

  // Challenges
  saveChallenge(challenge: Challenge): Promise<void>;
  getChallenge(id: string): Promise<Challenge | null>;
  deleteChallenge(id: string): Promise<void>;
  deleteExpiredChallenges(): Promise<void>;

  // Sessions
  createSession(session: Session): Promise<void>;
  getSession(id: string): Promise<Session | null>;
  deleteSession(id: string): Promise<void>;

  // Cross-device QR tokens
  createCrossDeviceToken(token: CrossDeviceToken): Promise<void>;
  getCrossDeviceToken(id: string): Promise<CrossDeviceToken | null>;
  approveCrossDeviceToken(
    id: string,
    userId: string,
    keyTransfer?: { approverEcdhPublicKey: string; wrappedAesKey: string },
  ): Promise<void>;
  deleteCrossDeviceToken(id: string): Promise<void>;
  deleteExpiredCrossDeviceTokens(): Promise<void>;

  // Roles (RBAC)
  getAllRoles(): Promise<Role[]>;
  grantRole(userId: string, roleName: string, grantedBy: string): Promise<void>;
  revokeRole(userId: string, roleName: string): Promise<void>;
  getUserRoles(userId: string): Promise<string[]>;
  getUsersWithRole(roleName: string): Promise<string[]>;

  // User preferences (key-value store per user)
  getUserPreferences(userId: string, keys: string[]): Promise<Record<string, string>>;
  setUserPreferences(userId: string, prefs: Record<string, string>): Promise<void>;

  // Instance identity & social graph
  getInstanceConfig(): Promise<InstanceConfig>;
  setInstanceConfig(fields: Partial<Pick<InstanceConfig, "name" | "description" | "canonicalUrl" | "parentUrl">>): Promise<void>;
  getGraphNodes(): Promise<GraphNode[]>;
  upsertGraphNode(node: GraphNode): Promise<void>;
  getGraphEdges(): Promise<GraphEdge[]>;
  upsertGraphEdge(edge: GraphEdge): Promise<void>;

}
