#!/usr/bin/env bash
# scripts/install.sh
# Server-side Primordia setup script.  Run this inside the cloned repo on a VM.
#
# Typically invoked by scripts/install-for-exe-dev.sh, which handles VM
# creation, port setup, and git clone before calling this script.
# Can also be run manually after cloning:
#
#   git clone https://primordia.exe.xyz/api/git ~/primordia
#   cd ~/primordia
#   bash scripts/install.sh

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────

if [[ -t 1 ]]; then
  BOLD="\033[1m"
  GREEN="\033[0;32m"
  CYAN="\033[0;36m"
  YELLOW="\033[0;33m"
  RED="\033[0;31m"
  RESET="\033[0m"
else
  BOLD="" GREEN="" CYAN="" YELLOW="" RED="" RESET=""
fi

info()    { echo -e "${CYAN}▸${RESET} $*"; }
success() { echo -e "${GREEN}✓${RESET} $*"; }
warn()    { echo -e "${YELLOW}⚠${RESET} $*"; }
die()     { echo -e "${RED}✗ $*${RESET}" >&2; exit 1; }

# ── Locate repo root ──────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REVERSE_PROXY_PORT="${REVERSE_PROXY_PORT:-3000}"

echo ""
echo -e "${BOLD}  Primordia Setup${RESET}"
echo -e "  Repo: ${INSTALL_DIR}"
echo ""

# ── Detect exe.dev ────────────────────────────────────────────────────────────

HOSTNAME_FQDN="$(hostname -f 2>/dev/null || hostname)"
if [[ "$HOSTNAME_FQDN" == *.exe.xyz ]]; then
  info "Detected exe.dev host: ${HOSTNAME_FQDN}"
  APP_URL="https://${HOSTNAME_FQDN}"
else
  warn "Not running on exe.dev — SSO login and the LLM gateway won't be available."
  APP_URL="http://localhost:${REVERSE_PROXY_PORT}"
fi
echo ""

# ── Install bun ───────────────────────────────────────────────────────────────

export PATH="$HOME/.bun/bin:$PATH"
if ! command -v bun &>/dev/null; then
  info "Installing bun..."
  curl -fsSL https://bun.sh/install | bash
  export PATH="$HOME/.bun/bin:$PATH"
fi
success "bun $(bun --version)"

# ── Write .env.local ──────────────────────────────────────────────────────────

ENV_FILE="${INSTALL_DIR}/.env.local"
if [[ ! -f "${ENV_FILE}" ]]; then
  cat > "${ENV_FILE}" << EOF
# Generated by Primordia installer — $(date -u '+%Y-%m-%d %H:%M:%S UTC')
REVERSE_PROXY_PORT=${REVERSE_PROXY_PORT}
EOF
  success "Wrote ${ENV_FILE}"
else
  info "Using existing ${ENV_FILE}"
fi

# ── Install dependencies ──────────────────────────────────────────────────────

info "Installing dependencies (bun install)..."
cd "${INSTALL_DIR}"
bun install --frozen-lockfile
success "Dependencies installed"

# ── Build production bundle ───────────────────────────────────────────────────

info "Building production bundle (bun run build)..."
bun run build
success "Build complete"

# ── Install systemd service ───────────────────────────────────────────────────

echo ""
info "Installing systemd service..."
bash "${INSTALL_DIR}/scripts/install-service.sh"

# ── Wait for ready ────────────────────────────────────────────────────────────

echo ""
info "Waiting for Primordia to be ready (up to 60 s)..."
for i in $(seq 1 30); do
  sleep 2
  if journalctl -u primordia-proxy -n 100 --no-pager 2>/dev/null | grep -q "Ready"; then
    echo ""
    success "Primordia is ready!"
    break
  fi
  if [[ $((i % 5)) -eq 0 ]]; then
    info "$((i * 2))s..."
  fi
done

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}${GREEN}  Primordia is running!${RESET}"
echo ""
echo -e "  Open:     ${BOLD}${APP_URL}${RESET}"
echo ""
if [[ "$HOSTNAME_FQDN" == *.exe.xyz ]]; then
  echo -e "  Sign in with your exe.dev account on the login page."
  echo -e "  The first user to sign in is automatically granted the admin role."
  echo -e "  You will be prompted for any missing API keys on first login."
else
  echo -e "  Register a passkey on the login page."
  echo -e "  The first user to register is automatically granted the admin role."
fi
echo ""
echo -e "  Useful commands:"
echo -e "    journalctl -u primordia-proxy -f         # tail proxy logs"
echo -e "    sudo systemctl restart primordia-proxy   # restart"
echo -e "    sudo systemctl stop primordia-proxy      # stop"
echo ""
