// app/api/openapi/route.ts
// Serves the OpenAPI spec, generating it on first request if the file
// doesn't already exist on disk.
//
// public/openapi.json is gitignored and generated by next-openapi-gen.
// This route lets the api-docs page work without any manual build step —
// the spec is produced automatically the first time /api-docs is opened.

import { existsSync, readFileSync } from 'fs';
import path from 'path';

const SPEC_PATH = path.join(process.cwd(), 'public', 'openapi.json');
const CONFIG_PATH = path.join(process.cwd(), 'openapi-gen.config.json');

// Module-level promise: all concurrent first-requests share a single generation run.
let genPromise: Promise<string> | null = null;

async function getSpec(): Promise<string> {
  // Fast path: file already exists from a previous request or manual generation.
  if (existsSync(SPEC_PATH)) {
    return readFileSync(SPEC_PATH, 'utf-8');
  }

  // Deduplicate: if generation is already in-flight, wait for that same promise.
  if (!genPromise) {
    genPromise = (async () => {
      const { generateProject } = await import('next-openapi-gen');
      await generateProject({ configPath: CONFIG_PATH });
      return readFileSync(SPEC_PATH, 'utf-8');
    })().finally(() => {
      // Reset so errors are retried on the next request.
      genPromise = null;
    });
  }

  return genPromise;
}

/**
 * @ignore
 */
export async function GET() {
  try {
    const spec = await getSpec();
    return new Response(spec, {
      headers: { 'Content-Type': 'application/json' },
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return new Response(JSON.stringify({ error: `Failed to generate OpenAPI spec: ${msg}` }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}
